import Link from "next/link";
import { ArrowRight, BrainCircuit, CheckCircle2, Cloud, Clock3, Sparkles, Target } from "lucide-react";

const features = [
  [BrainCircuit, "Pattern-first practice", "The 191-question Striver path is organised around the RB pattern vocabulary—not a random checklist."],
  [Clock3, "Adaptive recall", "Every solved question earns a personal review schedule so the right problems return at the right time."],
  [Cloud, "Progress that follows you", "Sign in once and keep your solves, review history, XP, and daily rhythm across devices."],
] as const;

export default function HomePage() {
  return <main className="landing">
    <nav className="landing-nav"><Link className="brand" href="/"><span className="mark">DS</span>Danish SDE Sheet</Link><div className="landing-nav-links"><a href="#how-it-works">How it works</a><Link className="nav-cta" href="/sheet">Open free sheet <ArrowRight size={15} /></Link></div></nav>
    <section className="landing-hero"><div className="hero-copy-block"><p className="landing-eyebrow"><Sparkles size={14} /> Pattern-first interview preparation</p><h1>Make your next interview answer feel familiar.</h1><p>One calm workspace for solving Striver’s SDE Sheet, learning the RB patterns behind it, and revising before the ideas fade.</p><div className="landing-actions"><Link className="landing-primary" href="/sheet">Start the free sheet <ArrowRight size={17} /></Link><a className="landing-secondary" href="#how-it-works">See the study loop</a></div><div className="trust-row"><span><CheckCircle2 size={15} /> 191 curated questions</span><span><CheckCircle2 size={15} /> LeetCode-ready links</span><span><CheckCircle2 size={15} /> Free to use</span></div></div>
      <div className="hero-preview" aria-label="Danish SDE study dashboard preview"><div className="preview-top"><span className="preview-brand"><i>DS</i> Today’s study room</span><span className="preview-streak">🔥 4 day streak</span></div><div className="preview-focus"><span>ACTIVE RECALL</span><h2>2 questions due today</h2><p>Explain the pattern before revealing the answer.</p><div className="preview-question"><div><b>Sliding Window Maximum</b><small>7-day interval · Stack & Queue</small></div><button>Review <ArrowRight size={14} /></button></div></div><div className="preview-bottom"><div><small>PROGRESS</small><b>28 <em>/ 191 solved</em></b></div><div className="mini-bars"><i/><i/><i/><i className="active"/><i className="active"/><i className="active"/><i/></div></div></div>
    </section>
    <section className="outcome-strip"><div><strong>Learn the signal</strong><span>Recognise the pattern before the code.</span></div><i/><div><strong>Practice deliberately</strong><span>Solve directly from the linked problem.</span></div><i/><div><strong>Recall over time</strong><span>Turn one solve into durable memory.</span></div></section>
    <section id="how-it-works" className="landing-section"><div className="section-intro"><p className="landing-eyebrow">A study system, not another list</p><h2>Give every hour of preparation a job.</h2><p>The sheet brings questions, resources, progress, and revision into the same simple loop.</p></div><div className="feature-grid">{features.map(([Icon, title, copy], index)=><article className="feature-card" key={title}><span className="feature-number">0{index + 1}</span><div className="feature-icon"><Icon size={22} /></div><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="landing-section rhythm-section"><div className="rhythm-copy"><p className="landing-eyebrow">Build a rhythm that lasts</p><h2>Solve today. Recall tomorrow. Grow for months.</h2><p>Mark a question solved, then let its own review schedule bring it back when recall matters most. You stay in control of every answer with Again, Hard, Good, and Easy.</p><Link href="/sheet" className="landing-primary">Build your study rhythm <ArrowRight size={17} /></Link></div><div className="rhythm-card"><div className="rhythm-head"><Target size={19}/><span>Question memory path</span></div><div className="timeline"><div><b>Today</b><span>Solve it deliberately</span></div><i/><div><b>Tomorrow</b><span>First active recall</span></div><i/><div><b>Week 1</b><span>Strengthen the pattern</span></div><i/><div><b>Later</b><span>Keep it interview-ready</span></div></div></div></section>
    <section className="landing-final"><p className="landing-eyebrow">Ready when you are</p><h2>Start with one pattern. Keep the momentum.</h2><p>No payment wall. Open the sheet and make today’s first solve count.</p><Link className="landing-primary" href="/sheet">Open Danish SDE Sheet <ArrowRight size={17} /></Link></section>
    <footer className="landing-footer"><Link className="brand" href="/"><span className="mark">DS</span>Danish SDE Sheet</Link><span>Built for deliberate DSA practice.</span><Link href="/sheet">Open the sheet</Link></footer>
  </main>;
}
